// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package uploader

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UploaderClient is the client API for Uploader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UploaderClient interface {
	Upload(ctx context.Context, in *FileTransferRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	UploadStream(ctx context.Context, opts ...grpc.CallOption) (Uploader_UploadStreamClient, error)
}

type uploaderClient struct {
	cc grpc.ClientConnInterface
}

func NewUploaderClient(cc grpc.ClientConnInterface) UploaderClient {
	return &uploaderClient{cc}
}

func (c *uploaderClient) Upload(ctx context.Context, in *FileTransferRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/uploader.Uploader/Upload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploaderClient) UploadStream(ctx context.Context, opts ...grpc.CallOption) (Uploader_UploadStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Uploader_ServiceDesc.Streams[0], "/uploader.Uploader/UploadStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &uploaderUploadStreamClient{stream}
	return x, nil
}

type Uploader_UploadStreamClient interface {
	Send(*FileStreamRequest) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type uploaderUploadStreamClient struct {
	grpc.ClientStream
}

func (x *uploaderUploadStreamClient) Send(m *FileStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *uploaderUploadStreamClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UploaderServer is the server API for Uploader service.
// All implementations must embed UnimplementedUploaderServer
// for forward compatibility
type UploaderServer interface {
	Upload(context.Context, *FileTransferRequest) (*empty.Empty, error)
	UploadStream(Uploader_UploadStreamServer) error
	mustEmbedUnimplementedUploaderServer()
}

// UnimplementedUploaderServer must be embedded to have forward compatible implementations.
type UnimplementedUploaderServer struct {
}

func (UnimplementedUploaderServer) Upload(context.Context, *FileTransferRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedUploaderServer) UploadStream(Uploader_UploadStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadStream not implemented")
}
func (UnimplementedUploaderServer) mustEmbedUnimplementedUploaderServer() {}

// UnsafeUploaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UploaderServer will
// result in compilation errors.
type UnsafeUploaderServer interface {
	mustEmbedUnimplementedUploaderServer()
}

func RegisterUploaderServer(s grpc.ServiceRegistrar, srv UploaderServer) {
	s.RegisterService(&Uploader_ServiceDesc, srv)
}

func _Uploader_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploaderServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uploader.Uploader/Upload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploaderServer).Upload(ctx, req.(*FileTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Uploader_UploadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UploaderServer).UploadStream(&uploaderUploadStreamServer{stream})
}

type Uploader_UploadStreamServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*FileStreamRequest, error)
	grpc.ServerStream
}

type uploaderUploadStreamServer struct {
	grpc.ServerStream
}

func (x *uploaderUploadStreamServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *uploaderUploadStreamServer) Recv() (*FileStreamRequest, error) {
	m := new(FileStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Uploader_ServiceDesc is the grpc.ServiceDesc for Uploader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Uploader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uploader.Uploader",
	HandlerType: (*UploaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _Uploader_Upload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadStream",
			Handler:       _Uploader_UploadStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "uploader/uploader.proto",
}
